### PR TITLE
Run collator with `--collator`

### PR DESCRIPTION
**Pull request by h4x3rotab**

### CODE REVIEW

**Comment by shawntabrizi** [comment]
@h4x3rotab can you link to the associated change?

**Comment by h4x3rotab** [comment]
In my understanding `--validator` on a collator once worked as `--collator` in the past. However when we connect to rococo-v1 public network, we found only the later way works. Sorry, I didn't dig into it to find the reason behind.

**Comment by bkchr** [comment]
https://github.com/paritytech/cumulus/blob/2662bcd3dda634bfafb9632da8fa1fe85a2d71d4/rococo-parachains/src/command.rs#L292

This is still considering both cli parameters. Not sure what you do differently in your code base.

**Comment by h4x3rotab** [comment]
Yeah, looks good for all the code I've read. Probably it's due to some other problems. We will look into this later this week.

**Pull request closed without merging**
