### PR TITLE
added bootnode on startup

### PR DESCRIPTION
**Pull request by JesseAbram**
As talked about in #77 , fix for issue, feel free to reject if not necessary

### CODE REVIEW

**Review by bkchr — COMMENTED** [review]
Why not add all nodes as bootnodes into the chainspec?

**Comment by JesseAbram** [comment]
Once they connect they connect to alice they seem to find each other fine, also I think I can only get the bootnodes after they launch. I could add alice's to bob then bob's and alice's to charlie etc, but since they find each other after connecting fine, Im not sure it is worthwhile?

**Comment by bkchr** [comment]
Yeah the only require one node to find each other. However, I think we should just add all, because I don't see any downside.

**Comment by JesseAbram** [comment]
makes sense, will do.

**Comment by bkchr** [comment]
(It will also make the code cleaner)

**Comment by JesseAbram** [comment]
ya, I see that, added it, one unintended consequence is that It has to connect to each node which adds idk like 4 seconds per node, is it still worth it? 
image

**Comment by bkchr** [comment]
We configure the ports in the config file. So, I don't see why you need to call the nodes to get this information.

For the node key I would propose we use something deterministic so that we can calculate it before starting the node.

But yeah, maybe we should just take your pr as it is

**Comment by bkchr** [comment]
Maybe you give this a short try, what I mentioned above. If that is too complicated, just lets merge your pr

**Comment by JesseAbram** [comment]
There may be a race condition in here that causes nodes to fail, will look into it when have more time, for now closing

**Pull request closed without merging**
